service: kmullaney-log-ingestion

useDotenv: true

provider:
  name: aws
  region: eu-west-1
  runtime: python3.9
  stage: dev
  timeout: 30
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: ticket
    description: "00056260"
  stackTags:
    owner: kmullaney
    reason: ticket
    description: "00056260"
  # Uncomment this line to use your own IAM role
  #role: arn:aws:iam::YourAccountNumber:role/YourIamRole
  environment:
    # Determines if logs are forwarded to New Relic Infrastructure
    INFRA_ENABLED: ${env:INFRA_ENABLED, "True"}
    # Your NewRelic license key
    LICENSE_KEY: ${env:LICENSE_KEY}
    # Determines if logs are forwarded to New Relic Logging
    LOGGING_ENABLED: ${env:LOGGING_ENABLED, "False"}
    # A boolean to determine if you want to output debug messages in the CloudWatch console
    DEBUG_LOGGING_ENABLED: ${env:DEBUG_LOGGING_ENABLED, "False"}

custom:
  pythonRequirements:
    dockerizePip: false
    fileName: ./src/requirements.txt

package:
  exclude:
    - ./**
  include:
    - ./LICENSE
    - ./src/function.py

functions:
  kmullaney-log-ingestion:
    description: Send log data from CloudWatch Logs to New Relic Infrastructure (Cloud Integrations) and New Relic Logging.
    handler: src/function.lambda_handler
    name: kmullaney-log-ingestion

plugins:
  - serverless-python-requirements
